[2023-12-19T19:26:58.800+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Auto_Insurance-v01.create_dim_tables scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-19T19:26:58.804+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Auto_Insurance-v01.create_dim_tables scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-19T19:26:58.804+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-19T19:26:58.811+0000] {taskinstance.py:1382} INFO - Executing <Task(SubDagOperator): create_dim_tables> on 2023-12-01 00:00:00+00:00
[2023-12-19T19:26:58.814+0000] {standard_task_runner.py:57} INFO - Started process 1180 to run task
[2023-12-19T19:26:58.816+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Auto_Insurance-v01', 'create_dim_tables', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/Auto_Insurance.py', '--cfg-path', '/tmp/tmpzprnmvw7']
[2023-12-19T19:26:58.817+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask create_dim_tables
[2023-12-19T19:26:58.847+0000] {task_command.py:416} INFO - Running <TaskInstance: Auto_Insurance-v01.create_dim_tables scheduled__2023-12-01T00:00:00+00:00 [running]> on host 757899fef296
[2023-12-19T19:26:58.888+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Auto_Insurance-v01' AIRFLOW_CTX_TASK_ID='create_dim_tables' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-19T19:26:58.891+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-19T19:26:58.897+0000] {subdag.py:174} INFO - Found existing DagRun: backfill__2023-12-01T00:00:00+00:00
[2023-12-19T19:31:31.412+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-12-19T19:31:31.413+0000] {process_utils.py:131} INFO - Sending 15 to group 1180. PIDs of all processes in the group: [1180]
[2023-12-19T19:31:31.414+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1180
[2023-12-19T19:31:31.414+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-19T19:31:31.421+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-12-19T19:31:31.423+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Auto_Insurance-v01, task_id=create_dim_tables, execution_date=20231201T000000, start_date=20231219T192658, end_date=20231219T193131
[2023-12-19T19:31:31.431+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task create_dim_tables (Task received SIGTERM signal; 1180)
[2023-12-19T19:31:31.443+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1180, status='terminated', exitcode=1, started='19:26:58') (1180) terminated with exit code 1
