[2023-12-21T16:49:55.532+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_HadHeartAttack_col scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:49:55.544+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_HadHeartAttack_col scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:49:55.545+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-21T16:49:55.558+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): remove_samples_with_nulls.remove_HadHeartAttack_col> on 2023-12-01 00:00:00+00:00
[2023-12-21T16:49:55.564+0000] {standard_task_runner.py:57} INFO - Started process 531 to run task
[2023-12-21T16:49:55.570+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Indicators_of_Heart_Disease_2022-v01.remove_samples_with_nulls', 'remove_samples_with_nulls.remove_HadHeartAttack_col', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/Indicators_of_Heart_Disease_2022.py', '--cfg-path', '/tmp/tmppcrtnapj']
[2023-12-21T16:49:55.574+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask remove_samples_with_nulls.remove_HadHeartAttack_col
[2023-12-21T16:49:55.628+0000] {task_command.py:416} INFO - Running <TaskInstance: Indicators_of_Heart_Disease_2022-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_HadHeartAttack_col scheduled__2023-12-01T00:00:00+00:00 [running]> on host 8e01071a5eb3
[2023-12-21T16:49:55.694+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Indicators_of_Heart_Disease_2022-v01.remove_samples_with_nulls' AIRFLOW_CTX_TASK_ID='remove_samples_with_nulls.remove_HadHeartAttack_col' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-21T16:49:55.696+0000] {sql.py:274} INFO - Executing: -- params: table_name, column_name
DELETE FROM indicators_of_heart_disease_2022_pipe
WHERE HadHeartAttack is NULL;
[2023-12-21T16:49:55.712+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:49:55.723+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:49:55.731+0000] {sql.py:418} INFO - Running statement: -- params: table_name, column_name
DELETE FROM indicators_of_heart_disease_2022_pipe
WHERE HadHeartAttack is NULL;, parameters: None
[2023-12-21T16:50:01.984+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 73966 waits for ShareLock on transaction 1141729; blocked by process 73964.
Process 73964 waits for ShareLock on transaction 1141728; blocked by process 73963.
Process 73963 waits for ShareLock on transaction 1141731; blocked by process 73966.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (4835,13) in relation "indicators_of_heart_disease_2022_pipe"

[2023-12-21T16:50:01.991+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Indicators_of_Heart_Disease_2022-v01.remove_samples_with_nulls, task_id=remove_samples_with_nulls.remove_HadHeartAttack_col, execution_date=20231201T000000, start_date=20231221T164955, end_date=20231221T165001
[2023-12-21T16:50:01.997+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task remove_samples_with_nulls.remove_HadHeartAttack_col (deadlock detected
DETAIL:  Process 73966 waits for ShareLock on transaction 1141729; blocked by process 73964.
Process 73964 waits for ShareLock on transaction 1141728; blocked by process 73963.
Process 73963 waits for ShareLock on transaction 1141731; blocked by process 73966.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (4835,13) in relation "indicators_of_heart_disease_2022_pipe"
; 531)
[2023-12-21T16:50:02.012+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:50:02.041+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
