[2023-12-20T02:50:49.566+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_Num_Of_Units_col scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-20T02:50:49.571+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_Num_Of_Units_col scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-20T02:50:49.572+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-20T02:50:49.587+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): remove_samples_with_nulls.remove_Num_Of_Units_col> on 2023-12-01 00:00:00+00:00
[2023-12-20T02:50:49.592+0000] {standard_task_runner.py:57} INFO - Started process 1249 to run task
[2023-12-20T02:50:49.597+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls', 'remove_samples_with_nulls.remove_Num_Of_Units_col', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/Gourmet_Food_Procurement_Data.py', '--cfg-path', '/tmp/tmpel8w6v34']
[2023-12-20T02:50:49.601+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask remove_samples_with_nulls.remove_Num_Of_Units_col
[2023-12-20T02:50:49.659+0000] {task_command.py:416} INFO - Running <TaskInstance: Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_Num_Of_Units_col scheduled__2023-12-01T00:00:00+00:00 [running]> on host 069170cec93a
[2023-12-20T02:50:49.703+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'remove_samples_with_nulls.remove_Num_Of_Units_col', field 'sql'. Template: '-- params: table_name, column_name\nDELETE FROM {{ params.table_name }}\nWHERE {{ params.column_name }} is NULL;'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'table_name'
[2023-12-20T02:50:49.705+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'table_name'
[2023-12-20T02:50:49.714+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls, task_id=remove_samples_with_nulls.remove_Num_Of_Units_col, execution_date=20231201T000000, start_date=20231220T025049, end_date=20231220T025049
[2023-12-20T02:50:49.721+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task remove_samples_with_nulls.remove_Num_Of_Units_col ('dict object' has no attribute 'table_name'; 1249)
[2023-12-20T02:50:49.729+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-20T02:50:49.754+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-20T18:04:54.074+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_Num_Of_Units_col scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-20T18:04:54.082+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_Num_Of_Units_col scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-20T18:04:54.082+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-20T18:04:54.094+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): remove_samples_with_nulls.remove_Num_Of_Units_col> on 2023-12-01 00:00:00+00:00
[2023-12-20T18:04:54.099+0000] {standard_task_runner.py:57} INFO - Started process 1665 to run task
[2023-12-20T18:04:54.114+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls', 'remove_samples_with_nulls.remove_Num_Of_Units_col', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/Gourmet_Food_Procurement_Data.py', '--cfg-path', '/tmp/tmpsh1oeh7m']
[2023-12-20T18:04:54.128+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask remove_samples_with_nulls.remove_Num_Of_Units_col
[2023-12-20T18:04:54.224+0000] {task_command.py:416} INFO - Running <TaskInstance: Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls.remove_samples_with_nulls.remove_Num_Of_Units_col scheduled__2023-12-01T00:00:00+00:00 [running]> on host 064e84e7d61d
[2023-12-20T18:04:54.313+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls' AIRFLOW_CTX_TASK_ID='remove_samples_with_nulls.remove_Num_Of_Units_col' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-20T18:04:54.315+0000] {sql.py:274} INFO - Executing: -- params: table_name, column_name
DELETE FROM gourmet_food_procurement_data_pipeline
WHERE Num_Of_Units is NULL;
[2023-12-20T18:04:54.324+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-20T18:04:54.333+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-20T18:04:54.343+0000] {sql.py:418} INFO - Running statement: -- params: table_name, column_name
DELETE FROM gourmet_food_procurement_data_pipeline
WHERE Num_Of_Units is NULL;, parameters: None
[2023-12-20T18:04:54.351+0000] {sql.py:427} INFO - Rows affected: 29
[2023-12-20T18:04:54.360+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Gourmet_Food_Procurement_Data-v01.remove_samples_with_nulls, task_id=remove_samples_with_nulls.remove_Num_Of_Units_col, execution_date=20231201T000000, start_date=20231220T180454, end_date=20231220T180454
[2023-12-20T18:04:54.407+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-20T18:04:54.427+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
