[2023-12-12T21:30:23.835+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: home_insurance_ds-v01.remove_replaced_dim_cols scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-12T21:30:23.839+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: home_insurance_ds-v01.remove_replaced_dim_cols scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-12T21:30:23.840+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-12T21:30:23.845+0000] {taskinstance.py:1382} INFO - Executing <Task(SubDagOperator): remove_replaced_dim_cols> on 2023-12-01 00:00:00+00:00
[2023-12-12T21:30:23.848+0000] {standard_task_runner.py:57} INFO - Started process 2429 to run task
[2023-12-12T21:30:23.850+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'home_insurance_ds-v01', 'remove_replaced_dim_cols', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/home_insurance_dataset.py', '--cfg-path', '/tmp/tmpylonko_c']
[2023-12-12T21:30:23.852+0000] {standard_task_runner.py:85} INFO - Job 95: Subtask remove_replaced_dim_cols
[2023-12-12T21:30:23.881+0000] {task_command.py:416} INFO - Running <TaskInstance: home_insurance_ds-v01.remove_replaced_dim_cols scheduled__2023-12-01T00:00:00+00:00 [running]> on host 7a94ca99eac6
[2023-12-12T21:30:23.919+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='home_insurance_ds-v01' AIRFLOW_CTX_TASK_ID='remove_replaced_dim_cols' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-12T21:30:23.922+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-12T21:30:23.928+0000] {subdag.py:174} INFO - Found existing DagRun: backfill__2023-12-01T00:00:00+00:00
[2023-12-12T21:34:21.429+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-12-12T21:34:21.431+0000] {process_utils.py:131} INFO - Sending 15 to group 2429. PIDs of all processes in the group: [2429]
[2023-12-12T21:34:21.431+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2429
[2023-12-12T21:34:21.431+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-12T21:34:21.438+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-12-12T21:34:21.440+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=home_insurance_ds-v01, task_id=remove_replaced_dim_cols, execution_date=20231201T000000, start_date=20231212T213023, end_date=20231212T213421
[2023-12-12T21:34:21.446+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 95 for task remove_replaced_dim_cols (Task received SIGTERM signal; 2429)
[2023-12-12T21:34:21.458+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2429, status='terminated', exitcode=1, started='21:30:23') (2429) terminated with exit code 1
